INDEXES = [
    {'table': 'tbl_betfair_betting_types', 'column': 'betting_type_name'},
    {'table': 'tbl_betfair_market_types', 'column': 'market_type'},
    {'table': 'tbl_betfair_market_status', 'column': 'market_status_name'},
    {'table': 'tbl_betfair_country_codes', 'column': 'country_code'},
    {'table': 'tbl_betfair_timezones', 'column': 'timezone'},
    {'table': 'tbl_betfair_markets', 'column': 'betfair_market_id'},
    {'table': 'tbl_betfair_markets', 'column': 'event_id'},
    {'table': 'tbl_betfair_market_definitions', 'column': 'version'},
    {'table': 'tbl_betfair_market_definitions', 'column': 'unix_timestamp'},
    {'table': 'tbl_betfair_market_definitions', 'column': 'betfair_market_id'},
    {'table': 'tbl_betfair_market_definitions', 'column': 'event_id'},
    {'table': 'tbl_betfair_runners', 'column': 'runner_name'},
    {'table': 'tbl_betfair_runners', 'column': 'betfair_id'},
    {'table': 'tbl_betfair_runner_status', 'column': 'status'},
    {'table': 'tbl_betfair_runner_status_updates', 'column': 'betfair_runner_table_id'},
    {'table': 'tbl_betfair_runner_status_updates', 'column': 'betfair_market_id'},
    {'table': 'tbl_betfair_runner_status_updates', 'column': 'event_id'},
    {'table': 'tbl_betfair_runner_status_updates', 'column': 'unix_timestamp'},
    {'table': 'tbl_betfair_last_traded_price', 'column': 'betfair_market_id'},
    {'table': 'tbl_betfair_last_traded_price', 'column': 'betfair_runner_table_id'},
    {'table': 'tbl_betfair_last_traded_price', 'column': 'event_id'},
    {'table': 'tbl_betfair_last_traded_price', 'column': 'unix_timestamp'}
]
