
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
