RAW_MARKET_CHANGE_UPDATE = {
    "op": "mcm",
    "clk": "9514068424",
    "pt": 1561827667935,
    "mc": [
        {
            "id": "1.159798672",
            "marketDefinition": {
                "bspMarket": False,
                "turnInPlayEnabled": True,
                "persistenceEnabled": True,
                "marketBaseRate": 5.0,
                "eventId": "29312140",
                "eventTypeId": "1",
                "numberOfWinners": 1,
                "bettingType": "ODDS",
                "marketType": "FIRST_HALF_GOALS_25",
                "marketTime": "2019-07-01T17:00:00.000Z",
                "suspendTime": "2019-07-01T17:00:00.000Z",
                "bspReconciled": False,
                "complete": True,
                "inPlay": False,
                "crossMatching": False,
                "runnersVoidable": False,
                "numberOfActiveRunners": 2,
                "betDelay": 0,
                "status": "OPEN",
                "runners": [
                    {"status": "ACTIVE", "sortPriority": 1, "id": 47972, "name": "Under 2.5 Goals"},
                    {"status": "INACTIVE", "sortPriority": 2, "id": 47973, "name": "Over 2.5 Goals"},
                ],
                "regulators": ["MR_INT"],
                "countryCode": "SE",
                "discountAllowed": True,
                "timezone": "GMT",
                "openDate": "2019-07-01T17:00:00.000Z",
                "version": 2840273014,
                "name": "First Half Goals 2.5",
                "eventName": "Djurgardens v Kalmar FF",
            },
        }
    ],
}
